### ISSUE TITLE
JsonRequestTranslator doesn't handle array attribute values correctly

### ISSUE THREAD

**Issue by ygrignon-sfdc** [att/xacml-3.0#6]
This example from the JSON Profile for XACML 1.0 spec should produce an attribute with 2 attribute values but actually produces an attribute with a single attribute value with an array list value.

```
{
  "Request": {
    "AccessSubject": [{
      "Attribute": [{
        "AttributeId": "urn:oasis:names:tc:xacml:2.0:subject:role",
        "Value": ["manager","administrator"]
      }]
    }]
  }
}
```

**Comment by ygrignon-sfdc** [comment]
@ssarangan created the issue

**Comment by ygrignon-sfdc** [comment]
@pdragosh I believe the id:code attribute in JsonRequestTranslatorTest.testAll()'s request is invalid based on the value definition in section 4.2.4 since it contains a mix of string and integer and the string does not represent a number.

**Comment by pdragosh** [comment]
Ok I think its merged now. Sorry for the wait.
